
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JarmuKolcsonzo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class jarmukategoria
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public jarmukategoria()
    {

        this.jarmu = new HashSet<jarmu>();

    }


    public int Id { get; set; }

    public string kategoriaNev { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<jarmu> jarmu { get; set; }

}

}
