
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JarmuKolcsonzo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class jarmu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public jarmu()
    {

        this.rendeles = new HashSet<rendeles>();

    }


    public int Id { get; set; }

    public string rendszam { get; set; }

    public int kategoriaId { get; set; }

    public string tipus { get; set; }

    public string modell { get; set; }

    public Nullable<int> ferohely { get; set; }

    public Nullable<double> fogyasztas { get; set; }

    public bool elerheto { get; set; }

    public bool szervizben { get; set; }

    public Nullable<System.DateTime> szervizDatum { get; set; }

    public Nullable<System.DateTime> muszakiDatum { get; set; }

    public Nullable<System.DateTime> beszerzesDatum { get; set; }



    public virtual jarmukategoria jarmukategoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<rendeles> rendeles { get; set; }

}

}
