

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JarmuKolcsonzo.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class JKContext : DbContext
{
    public JKContext()
        : base("name=JKContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<jarmu> jarmu { get; set; }

    public virtual DbSet<jarmukategoria> jarmukategoria { get; set; }

    public virtual DbSet<ugyfel> ugyfel { get; set; }

    public virtual DbSet<rendeles> rendeles { get; set; }

}

}

