
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JarmuKolcsonzo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ugyfel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ugyfel()
    {

        this.rendeles = new HashSet<rendeles>();

    }


    public int id { get; set; }

    public string vezeteknev { get; set; }

    public string keresztnev { get; set; }

    public string varos { get; set; }

    public string cim { get; set; }

    public int irszam { get; set; }

    public string telefonszam { get; set; }

    public string email { get; set; }

    public int pont { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<rendeles> rendeles { get; set; }

}

}
